name: Build Tutorials for .NET 9.0
permissions:
  contents: read
  packages: read
  
on:
  push:
  pull_request:
    branches: [ master, main, develop/* ]
    paths:
    - '**.cs'
    - '**.csproj'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

jobs:
  build-and-test-net9:
    name: test-${{matrix.os}}-${{matrix.customtesttarget}}-${{matrix.csproj}}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false    
      matrix:
        os: [ubuntu-latest, windows-2025, macOS-latest]    
        csproj: [Tutorials]
        include:
          - framework: 'net9.0'
            dotnet-version: '9.0.x'
            configuration: 'Release'
            customtesttarget: net9.0
            
    env:
      OS: ${{ matrix.os }}
      DOTNET_VERSION: ${{ matrix.dotnet-version }}
      CONFIGURATION:  ${{ matrix.configuration }}
      CSPROJ: ${{ matrix.csproj }}
      CSPROJECT: "./${{ matrix.csproj }}.sln"

    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0
    
    - name: Setup .NET ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: ${{ matrix.dotnet-version }}

    - name: Set Cloud Version
      shell: pwsh
      run: ./.azurepipelines/set-version.ps1

    - name: Build
      run: |
           dotnet nuget add source "https://nuget.pkg.github.com/technosoftware-gmbh/index.json" -n github  -u build -p "${{ secrets.GITHUB_TOKEN }}" --store-password-in-clear-text
           dotnet build ${{ env.CSPROJECT }} --force --framework ${{ matrix.framework }} --configuration ${{ matrix.configuration }} /p:CustomTestTarget=${{ matrix.customtesttarget }}
